# @package _global_
optim:
  eval_interval: 5000
  log_interval: 50
  eval_iters: 50
  eval_only: false
  always_save_checkpoint: true
  init_from: scratch
  init_from_ckpt: ""
  continue_from_subset_size: 0
  batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 0.00001
  max_iters: 1000000
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: true
  warmup_iters: 2000
  lr_decay_iters: ${optim.max_iters}
  min_lr: ${optim.learning_rate}
  seed: 1337
  offline_single_epoch: true
  offline_eval_full: false
  offline_train_subset_size: 0
  offline_train_shuffle: false
  offline_target_type: tokens
  offline_eval_diagnostics: false
  offline_eval_diagnostics_loss_threshold: 1.0
  final_eval_on_exit: true
  s5_eval_n: 5000
  s5_eval_batch_size: 512
  s5_eval_seed: 123
  save_every: 0
